import React from 'react';
import { Document, Page, Text, View, StyleSheet, PDFDownloadLink } from '@react-pdf/renderer';
import { FileText } from 'lucide-react';

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica' },
  header: { fontSize: 24, marginBottom: 10, textAlign: 'center', color: '#1a365d' },
  syntheticBanner: { fontSize: 10, marginBottom: 20, textAlign: 'center', color: '#a23b2e', backgroundColor: '#fef2f2', padding: 6, borderRadius: 4 },
  subheader: { fontSize: 14, marginBottom: 30, textAlign: 'center', color: '#4a5568' },
  section: { margin: 10, padding: 10 },
  row: { flexDirection: 'row', justifyContent: 'space-between', borderBottom: '1 solid #e2e8f0', paddingBottom: 5, marginBottom: 10 },
  label: { fontSize: 12, color: '#4a5568' },
  value: { fontSize: 12, fontWeight: 'bold', color: '#2d3748' },
  title: { fontSize: 16, marginBottom: 15, borderBottom: '2 solid #3182ce', paddingBottom: 5 },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, textAlign: 'center', fontSize: 10, color: '#a0aec0' }
});

const ReportDocument = ({ data }: { data: any }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <Text style={styles.header}>Raksha MMR Impact Report</Text>
      {data.hasSynthetic && (
        <Text style={styles.syntheticBanner}>⚠ SYNTHETIC DEMO DATA — Numbers below are from seeded test data, not real incidents.</Text>
      )}
      <Text style={styles.subheader}>Generated on {new Date().toLocaleDateString()}</Text>
      
      <View style={styles.section}>
        <Text style={styles.title}>Executive Summary</Text>
        <View style={styles.row}>
          <Text style={styles.label}>Total Secure Reports</Text>
          <Text style={styles.value}>{data.total}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Critical Cases</Text>
          <Text style={styles.value}>{data.critical}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Cases Dispatched</Text>
          <Text style={styles.value}>{data.dispatched}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Cases Rescued</Text>
          <Text style={styles.value}>{data.rescued}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Cases Closed</Text>
          <Text style={styles.value}>{data.closed}</Text>
        </View>
      </View>

      <View style={styles.section}>
        <Text style={styles.title}>Incidents by Jurisdiction</Text>
        {Object.entries(data.jurisdictions || {}).map(([jurisdiction, count]: any) => (
          <View style={styles.row} key={jurisdiction}>
            <Text style={styles.label}>{jurisdiction}</Text>
            <Text style={styles.value}>{count} incident(s)</Text>
          </View>
        ))}
      </View>

      <View style={styles.section}>
        <Text style={styles.title}>Team Assignment Breakdown</Text>
        {Object.entries(data.teams || {}).map(([team, count]: any) => (
          <View style={styles.row} key={team}>
            <Text style={styles.label}>{team}</Text>
            <Text style={styles.value}>{count} incident(s)</Text>
          </View>
        ))}
        {Object.keys(data.teams || {}).length === 0 && (
          <Text style={styles.label}>No teams dispatched currently.</Text>
        )}
      </View>

      <Text style={styles.footer}>
        This is a confidential document generated by the Raksha MMR platform.
      </Text>
    </Page>
  </Document>
);

export const ReportGenerator = ({ tickets }: { tickets: any[] }) => {
  // Aggregate metrics using real status enum values
  const stats = {
    total: tickets.length,
    critical: tickets.filter(t => t.priority === 'Critical').length,
    dispatched: tickets.filter(t => t.status === 'DISPATCHED').length,
    rescued: tickets.filter(t => t.status === 'RESCUED').length,
    closed: tickets.filter(t => t.status === 'CLOSED').length,
    hasSynthetic: tickets.some(t => t.isSynthetic),
    jurisdictions: tickets.reduce((acc, t) => {
      const jur = t.district_id || 'Unknown';
      acc[jur] = (acc[jur] || 0) + 1;
      return acc;
    }, {} as Record<string, number>),
    teams: tickets.reduce((acc, t) => {
      if (t.assigned_team) {
        acc[t.assigned_team] = (acc[t.assigned_team] || 0) + 1;
      }
      return acc;
    }, {} as Record<string, number>)
  };

  return (
    <PDFDownloadLink 
      document={<ReportDocument data={stats} />} 
      fileName={`Raksha_MMR_Report_${new Date().toISOString().split('T')[0]}.pdf`}
      className="flex items-center gap-2 px-4 py-2 bg-[var(--teal)]/90 backdrop-blur text-white text-[13px] font-semibold rounded-lg hover:bg-[var(--teal)] transition shadow-sm"
    >
      <FileText className="w-4 h-4" />
      Generate Impact Report
    </PDFDownloadLink>
  );
};
